queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=Checks
      - check-success=Documentation
      - check-success=Unit tests (py36)
      - check-success=Unit tests (py37)
      - check-success=Unit tests (py38)
      - check-success=Unit tests (py39)
      - check-success=Unit tests (py310)


pull_request_rules:

  - name: Automatic merge on approval
    actions:
      queue:
        name: default
        method: rebase
        rebase_fallback: none
    conditions:
      - label!=no-mergify
      - -draft
      - approved-reviews-by=@fedora-infra/team
      - "#changes-requested-reviews-by=0"
      - check-success=Checks
      - check-success=Documentation
      - check-success=Unit tests (py36)
      - check-success=Unit tests (py37)
      - check-success=Unit tests (py38)
      - check-success=Unit tests (py39)
      - check-success=Unit tests (py310)

  - name: Automatic merge Dependabot PRs
    actions:
      queue:
        name: default
        method: rebase
        rebase_fallback: none
    conditions:
      - label!=no-mergify
      - -draft
      - author=dependabot[bot]
      - approved-reviews-by=github-actions[bot]
      - "#changes-requested-reviews-by=0"
      - check-success=Checks
      - check-success=Documentation
      - check-success=Unit tests (py36)
      - check-success=Unit tests (py37)
      - check-success=Unit tests (py38)
      - check-success=Unit tests (py39)
      - check-success=Unit tests (py310)
