queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=Checks
      - check-success=Documentation
      - check-success=Unit tests (py37)
      - check-success=Unit tests (py38)
      - check-success=Unit tests (py39)
      - check-success=Unit tests (py310)


pull_request_rules:

  - name: Merge on approval
    actions:
      queue:
        name: default
        method: rebase
    conditions:
      - label!=no-mergify
      - -draft
      - approved-reviews-by=@fedora-infra/fedora-infrastructure-developers
      - "#changes-requested-reviews-by=0"
      - check-success=Checks
      - check-success=Documentation
      - check-success=Unit tests (py37)
      - check-success=Unit tests (py38)
      - check-success=Unit tests (py39)
      - check-success=Unit tests (py310)
