repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        args:
          - --py36-plus

  # https://black.readthedocs.io/en/stable/integrations/source_version_control.html
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--check", "--diff"]

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["-c", "--df"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: ["-ll", "-x", "*/tests/*"]
        # All files in one go to get a single report
        require_serial: true

#  - repo: https://github.com/myint/rstcheck
#    rev: 3f92957
#    hooks:
#      - id: rstcheck
#        exclude: "news/_template.rst"
#        additional_dependencies: [sphinx]


  - repo: local
    hooks:
      - id: liccheck
        name: liccheck
        entry: ./devel/run-liccheck.sh
        files: "(pyproject.toml|poetry.lock)"
        pass_filenames: false
        language: script
