repos:
  # Generic hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # https://black.readthedocs.io/en/stable/integrations/source_version_control.html
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: ["--diff"]

  # Ruff
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--diff"]

#  - repo: https://github.com/myint/rstcheck
#    rev: 3f92957
#    hooks:
#      - id: rstcheck
#        exclude: "news/_template.rst"
#        additional_dependencies: [sphinx]

  # License headers
  - repo: https://github.com/fsfe/reuse-tool
    rev: v4.0.3
    hooks:
      - id: reuse
