on:
  push:
    branches:
      - stable
      - develop
  pull_request:
    branches:
      - stable
      - develop

name: Tests

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    container: fedorapython/fedora-python-tox:latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: dnf install -y pre-commit git poetry

      - name: Mark the working directory as safe for Git
        run: git config --global --add safe.directory $PWD

      - name: Run pre-commit checks
        run: pre-commit run --all-files

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    container: fedorapython/fedora-python-tox:latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: dnf install -y krb5-devel tox

      - name: Build the docs
        run: tox -e docs

      # - name: Save the docs
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: docs
      #     path: sqlalchemy_helpers/docs/_build/html

  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    container: fedorapython/fedora-python-tox:latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: dnf install -y krb5-devel tox

      - name: Run the tests
        run: tox -e ${{ matrix.pyver }}-${{ matrix.sqlaver }}

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1
      #   with:
      #     name: ${{ matrix.tox_env }}
      #     flags: unittests
      #     env_vars: PYTHON
      #     fail_ci_if_error: true

    strategy:
      matrix:
        pyver:
          - py37
          - py38
          - py39
          - py310
        sqlaver:
          - sqla1
          - sqla2
