on:
  push:
    branches:
      - stable
      - develop
  pull_request:
    branches:
      - stable
      - develop

name: Tests

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # - name: Install krb5-devel for python-gssapi
      #   run: sudo apt-get install krb5-config libkrb5-dev

      - name: Install pre-commit and poetry
        run: pip install pre-commit poetry

      - name: Install the project with poetry
        run: poetry install

      - name: Run pre-commit checks
        run: pre-commit run --all-files

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install krb5-devel for python-gssapi
        run: sudo apt-get install krb5-config libkrb5-dev

      - name: Install tox
        run: pip install tox

      - name: Build the docs
        run: tox -e docs

      # - name: Save the docs
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: docs
      #     path: sqlalchemy_helpers/docs/_build/html

  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run unit tests with Tox
        uses: fedora-python/tox-github-action@master
        with:
          tox_env: ${{ matrix.tox_env }}
          dnf_install: krb5-devel libpq-devel

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1
      #   with:
      #     name: ${{ matrix.tox_env }}
      #     flags: unittests
      #     env_vars: PYTHON
      #     fail_ci_if_error: true

    strategy:
      matrix:
        tox_env:
          - py37
          - py38
          - py39
          - py310
